name: Hello world!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say it
        run: echo "Hello world!"
      - name: Say date
        run: date
      - name: Say contents
        run: ls -l